[toolchain]
anchor_version = "1.2.0"
solana_version = "4.1.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tenet = "7pLYmJXsTJW7vWuT9BwYqNCWUDXp8SR1JKmKYNofAECf"
tenet_devnet = "6ZXVyvYPPLhoMTF4BDa2M3SLpWRvHxPCLjD9WFQzBdNm"

[programs.devnet]
tenet = "7pLYmJXsTJW7vWuT9BwYqNCWUDXp8SR1JKmKYNofAECf"
tenet_devnet = "6ZXVyvYPPLhoMTF4BDa2M3SLpWRvHxPCLjD9WFQzBdNm"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node --test packages/domain/test/accounting.test.ts"
