/**
 * The generated Kit client, checked against data the RUST side verified.
 *
 *   node --import tsx --test packages/sdk/test/client.test.ts
 *
 * Codama generated the client from the IDL; these tests make sure it agrees
 * with what the program actually does, rather than trusting the generator.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { getAddressDecoder, type Address } from "@solana/kit";
import * as sdk from "../src/index.ts";
import {
  findActiveUsdcVaultPda, findCircleAssetPda, findCirclePda, findConfigPda,
  findEpochEscrowPda, findEpochPda, findMandatePda, findMemberPda, findReceiptPda,
  findRegistryEntryPda, findVaultAuthorityPda, findVaultPda,
  getCircleSize, pda, TENET_PROGRAM_ADDRESS,
  TENET_ERROR__NOT_UPGRADE_AUTHORITY, TENET_ERROR__REDEMPTION_PENDING,
  TENET_ERROR__ASSET_NOT_IN_SNAPSHOT,
  u64, contribute, PROGRAM_ID,
} from "../src/index.ts";

const vectors = JSON.parse(
  readFileSync(new URL("../../../tests/vectors/pda.json", import.meta.url), "utf8"),
);
const addr = (hex: string): Address => getAddressDecoder().decode(Buffer.from(hex, "hex"));

test("program address agrees across IDL, SDK seeds and vectors", () => {
  assert.equal(TENET_PROGRAM_ADDRESS, PROGRAM_ID);
  assert.equal(vectors.programId, PROGRAM_ID);
});

test("generated PDA helpers reproduce every Rust-verified derivation they cover", async () => {
  // tests/vectors/pda.json was replayed through the program's own
  // find_program_address (pda_vectors.rs). Each generated helper must land on
  // the same address and bump — a mismatch would address the wrong account.
  const helpers: Record<string, (a: string[]) => Promise<readonly [Address, number]>> = {
    config: () => findConfigPda(),
    mandate: (a) => findMandatePda({ mandateSeed: addr(a[0]) }),
    registry: (a) => findRegistryEntryPda({ mint: addr(a[0]) }),
    circle: (a) => findCirclePda({ mandate: addr(a[0]) }),
    circle_asset: (a) => findCircleAssetPda({ circle: addr(a[0]), mint: addr(a[1]) }),
    vault_authority: (a) => findVaultAuthorityPda({ circle: addr(a[0]) }),
    asset_vault: (a) => findVaultPda({ circle: addr(a[0]), mint: addr(a[1]) }),
    usdc_vault: (a) => findActiveUsdcVaultPda({ circle: addr(a[0]) }),
    epoch: (a) => findEpochPda({ circle: addr(a[0]), index: BigInt(a[1]) }),
    epoch_escrow: (a) => findEpochEscrowPda({ circle: addr(a[0]), index: BigInt(a[1]) }),
    receipt: (a) => findReceiptPda({ epoch: addr(a[0]), contributor: addr(a[1]) }),
    member: (a) => findMemberPda({ circle: addr(a[0]), memberOwner: addr(a[1]) }),
  };
  let checked = 0;
  for (const v of vectors.vectors) {
    const h = helpers[v.fn];
    if (!h) continue; // not generated by Codama; covered by src/pda.ts
    const [address, bump] = await h(v.args);
    assert.equal(address, addr(v.address), `${v.fn}(${v.args.join(", ")})`);
    assert.equal(bump, v.bump, `${v.fn} bump`);
    checked++;
  }
  // Config has one vector; the other eleven generated helpers have six each.
  assert.equal(checked, 1 + 11 * 6, "every generated helper was exercised");
});

test("stable pda helpers reproduce EVERY Rust-verified derivation", async () => {
  const camel = (s: string) => s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
  let checked = 0;
  for (const v of vectors.vectors) {
    const name = camel(v.fn) as keyof typeof pda;
    const f = pda[name] as (...a: unknown[]) => Promise<readonly [Address, number]>;
    assert.ok(f, `pda.${name} exists`);
    // Keys are 64 hex chars; integer seeds are decimal strings.
    const args = v.args.map((x: string) => (/^[0-9a-f]{64}$/.test(x) ? addr(x) : BigInt(x)));
    const [address, bump] = await f(...args);
    assert.equal(address, addr(v.address), `${v.fn}(${v.args.join(", ")})`);
    assert.equal(bump, v.bump, `${v.fn} bump`);
    checked++;
  }
  assert.equal(checked, vectors.vectors.length);
});

test("generated error codes match what the on-chain tests observed", () => {
  // Codes seen in the LiteSVM mutation runs (tests/program).
  assert.equal(TENET_ERROR__NOT_UPGRADE_AUTHORITY, 6062);
  assert.equal(TENET_ERROR__REDEMPTION_PENDING, 6074);
  assert.equal(TENET_ERROR__ASSET_NOT_IN_SNAPSHOT, 6075);
});

test("generated account layout matches the program", () => {
  // 8-byte discriminator + Circle::INIT_SPACE (asserted field-by-field in
  // programs/tenet/src/state/mod.rs `circle_holds_no_token_balances`).
  assert.equal(getCircleSize(), 8 + 88);
});

test("amounts must be bigint: numbers are refused, not silently rounded", async () => {
  assert.equal(u64(1n, "x"), 1n);
  assert.throws(() => u64(1, "amount"), TypeError);
  assert.throws(() => u64(2 ** 53 + 1, "amount"), TypeError); // the V-018 case
  assert.throws(() => u64(-1n, "amount"), RangeError);
  assert.throws(() => u64(1n << 64n, "amount"), RangeError);

  // The wrapped builder refuses a number even when TypeScript is bypassed.
  await assert.rejects(
    async () => contribute({ amount: 5_000_000 } as never),
    TypeError,
  );
});

test("package root does not expose raw amount-bearing generated builders", () => {
  assert.equal("getContributeInstructionAsync" in sdk, false);
  assert.equal("getOpenEpochInstructionAsync" in sdk, false);
  assert.equal("getInitiateRedemptionInstructionAsync" in sdk, false);
  assert.equal("getCreateMandateInstructionAsync" in sdk, false);
});
